import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/context/SidebarContext";
import { Navbar, SidebarLeft, SidebarRight } from "@/components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Reddit - Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0E1113] text-white`}>
        <SidebarProvider>
        <Navbar />  {/* Fixed Top Bar */}
        <div className="flex justify-center max-w-400 mx-auto">
          <SidebarLeft />  {/* Left Sidebar */}
          <main className="flex-1">
            {children}  {/* Render page content here */}
          </main>
          <SidebarRight />  {/* Right Sidebar */}
        </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
